"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e1d643ps!w4@own_2^*700+^tno8^-lln!f)=kbp%1tbqt)_t%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console_debug': {
            'class': 'logging.StreamHandler',
            'formatter': 'console_debug',
            'level': 'DEBUG',
            'filters': ['require_debug_true']
        },
        'console_warning': {
            'class': 'logging.StreamHandler',
            'formatter': 'console_warning',
            'level': 'WARNING',
            'filters': ['require_debug_true']
        },
        'console_error': {
            'class': 'logging.StreamHandler',
            'formatter': 'console_error',
            'level': 'ERROR',
            'filters': ['require_debug_true']
        },
        'general': {
            'class': 'logging.FileHandler',
            'filename': 'general.log',
            'formatter': 'general',
            'level': 'INFO',
            'filters': ['require_debug_false']
        },
        'errors': {
            'class': 'logging.FileHandler',
            'filename': 'errors.log',
            'formatter': 'errors',
            'level': 'ERROR'
        },
        'security': {
            'class': 'logging.FileHandler',
            'filename': 'security.log',
            'formatter': 'security',
            'level': 'INFO'
        },
        'mail_admins': {
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'mail_admins',
            'level': 'ERROR',
            'filters': ['require_debug_false']
        }
    },
    'formatters': {
        'console_debug': {
            'format': '%(asctime)s, %(levelname)s, %(message)s'
        },
        'console_warning': {
            'format': '%(asctime)s, %(levelname)s, %(message)s, %(pathname)s'
        },
        'console_error': {
            'format': '%(asctime)s, %(levelname)s, %(message)s, %(pathname)s, '
                      '%(exc_info)s'
        },
        'general': {
            'format': '%(asctime)s, %(levelname)s, %(module)s, %(message)s'
        },
        'errors': {
            'format': '%(asctime)s, %(levelname)s, %(message)s, %(pathname)s, '
                      '%(exc_info)s'
        },
        'security': {
            'format': '%(asctime)s, %(levelname)s, %(module)s, %(message)s'
        },
        'mail_admins': {
            'format': '%(asctime)s, %(levelname)s, %(message)s, %(pathname)s'
        }
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console_debug', 'console_warning', 'console_error',
                         'general']
        },
        'django.request': {
            'handlers': ['errors', 'mail_admins']
        },
        'django.server': {
            'handlers': ['errors', 'mail_admins']
        },
        'django.template': {
            'handlers': ['errors']
        },
        'django.db.backends': {
            'handlers': ['errors']
        },
        'django.security': {
            'handlers': ['security']
        }
    }
}
